### ISSUE TITLE
Homepage struktur besprechen

### ISSUE THREAD

**Issue by markbrough** [okfde/2030-watch.de#101]
Was sind die Hauptthemen der Website? Wie kann man diese Themen besser strukturieren?

**Comment by markbrough** [comment]
zB: 
- neuer Aufruf auf Landing Page zur Monitoring Seite, da zentrale Angelegenheit (siehe PWYF 2013) - zB einen Screenshot der Visualisierung [statt grauen Button]
- Blog weiter oben, da aktuelles
- Was will man als 1st impression kommunizieren (aktuell: Video und Überschrift) - besonders ganz oben, "above the fold"? Es sollten die Top 3 wichtige Themen auf Landing Page hervor gehoben werden.

**Comment by ClaudiaSchwegmann** [comment]
Kann nur zustimmen das die Landing Page besser werden muss: im Bezug auf Text, Struktur und Design.

**Comment by Jzfelde** [comment]
Die Frage ist, was unsere wichtigsten Themen sind, die ganz oben auf der Landing Page sein sollten. Ich hätte spontan gesagt. Monitoring, Daten und Blog. Bist Du d'accord @ClaudiaSchwegmann ?

**Comment by jengeb** [comment]
I close this issue because there will be a new webpage soon.
