### ISSUE TITLE
Links zur Datenquelle bei Einzelindikatoren in neuem Tab öffnen

### ISSUE THREAD

**Issue by knutator2** [okfde/2030-watch.de#110]
Damit wärs leichter, zwischen Quellen und den Daten von 2030 Watch hin- und herzuspringen

**Comment by ClaudiaSchwegmann** [comment]
+1

**Comment by mattfullerton** [comment]
-1...

https://css-tricks.com/use-target_blank/

**Comment by markbrough** [comment]
-1 aus den selben Gründen wie @mattfullerton

**Comment by jengeb** [comment]
This issue refers to the old/current webpage. There will be a new version soon. :-)
