### ISSUE TITLE
Tweak optimum value UI

### ISSUE THREAD

**Issue by optikfluffel** [okfde/2030-watch.de#113]
It would be great to have an additional indicator wether having more or less than the optimum value is better. In the compare view it's somewhat easy to find out but otherwise it isn't.

Example:
![screen shot 2016-10-13 at 18 26 22](https://cloud.githubusercontent.com/assets/379915/19357751/399d885e-9173-11e6-9262-505db39beaed.png)

Maybe `< 3`, `3↓` or `max. 3` would work.

**Comment by mattfullerton** [comment]
Closed by 0563b89

**Comment by mattfullerton** [comment]
Closed by 0563b89 - preview at https://dev.2030-watch.de/en/monitoring/laendervergleich/
