### ISSUE TITLE
Neue Prioritäten für Webseite für 2.Woche Nov

### ISSUE THREAD

**Issue by ClaudiaSchwegmann** [okfde/2030-watch.de#32]
Lieber Christian
In dieser Woche wollen wir die Webseite etwas bekannter machen. Folgende Prios sehe ich für die nächsten 2-3 Tage

1) Indikatoren offline stellen: Die beiden Indikatoren "Finanzielle Abhängigkeit im Alter" und "Angepasste Arbeitslosenrate" offline stellen. Der erste Indikator ist eine Fehlinterpretation, der zweite ist doppelt.
2) Indikatoren hochladen:Sobald Johanna, Sina und ich weitere Indikatoren im D-Stadium haben, diese Indikatoren hochladen.
3) Farben: Dazu hatte Dir Johanna vorgestern (?) ja schon eine email geschickt.
4) BugFix: Die Sortierung der Punkte im Länder Vergleich sollte immer nach Farben sein - bisher verändert sie sich wenn man ein neues Land wählt.
5) BugFix: Wenn man auf SDG 5 in der ersten Viz klickt erscheinen zwei Indikatoren, Anteil Frauen in nationalen Parlamenten und Anteil biologischer Landwirtschaft !!! In dem Datensatz zu biologischer Landwirtschaft ist SDG 5 aber nicht angegeben, sondern nur SDG 15. Könnte sein, dass dieses Problem auch bei anderen SDGs zutrifft.
6) Funktionalität: Filter für offizielle und inoffizielle Indikatoren. Inoffizielle Indikatoren sind alle mit OKF bezeichneten Indikatoren. Offizielle sind alle anderen.
7) Funktionalität: Unter der dritten Viz sollte die deutsche Langbeschreibung des Indikatoren als Textfeld stehen.
8) Funktionalität: Bei der ersten Viz sind jetzt alle SDGs blass. Sie werden nur stark, wenn man drüber geht. Schöner wäre es, wenn alle SDGs gut zu sehen sind und beim Drübergehen die SDGs auf andere Weise gekennzeichnet werden. Z.B. indem sie etwas größer werden, oder eine Rand bekommen ...

Danke
Claudia

**Comment by jengeb** [comment]
This issue refers to the old/current webpage. There will be a new version soon.
