### ISSUE TITLE
Prioritäten vor dem Soft-Launch

### ISSUE THREAD

**Issue by ClaudiaSchwegmann** [okfde/2030-watch.de#4]
1) Footer und Impressum, incl. Logos (siehe Claudias Mails vom 28. Oktober)
2) Hintergrund erstmal weg
3) Etwas mehr Abstand zwischen Logo - 1 Viz - 2 Viz - 3 Viz - Footer
4) Die Einzeldaten sortieren sich nach Farbe in 1.Viz und 2.Viz in Chrome (und Firefox)
5) Kontaktdaten
6) Auf Einzelindikatorebene sind die Länder nach Bewertung sortiert

**Comment by cpape** [comment]
1) erledigt
2) erledigt
3) ist das nun ok so?
4) erledigt
5) erledigt
6) Laender sind nach _Wert_ sortiert. Fuer sinnvolle Sortierung nach Score braucht eine stabile Sortierfunktion.

**Comment by ClaudiaSchwegmann** [comment]
Super. Danke! das ist viel besser! :)

Habe eben nochmal eine Fonts Issue geöffnet. Aber meiner Meinung nach können wir life schalten. 
Als nächste Prio sehe ich
1) Fonts
2) Merging der von Johanna und mir aktualisierten online Dokumente
3) Das Hochladen von D-Dokumenten aus dem gescored Ordner
4) Bei der Einzelindikator Viz: die Balken breiter machen und die Beschriftung lesbarer. Außerdem sollten die Länder, für die es keine Daten gibt, nicht sichtbar sein.
4) Die nächsten Filter einbauen: Ministerien, Offiziell/Inoffiziell
6) Bei dem SDG Filter: Jetzt sind alle SDG Bilder blass. Die Farbe wird kräftiger, wenn man drüber geht mit der Maus. Kann man es so machen, dass die kräftige Farbe bleibt, wenn man einen SDG Ziel ausgewählt hat. Und dann wäre noch ein 18 Button gut für "Alle SDGs", damit man weiß wie man wieder zur Gesamtschau kommt.
7) Bei den Ländervergleichen die Möglichkeit bieten, mehr bzw. andere Länder auszuwählen.
8) Wenn man jetzt auf ein Land klickt, dann verschieben sich die Punkte in den beiden anderen Ländern, dass ist seltsam :)

**Comment by cpape** [comment]
2) erledigt

9) der Klick auf ein Land erlaubt einen direkten Vergleich der Indikatorenfarben, die Indikatoren korrespondieren dann ueber alle drei Laender hinweg

**Comment by ClaudiaSchwegmann** [comment]
Prima. Danke. Der nächste große Schritt ist nun, dass wir die Webseite auch Geldgebern zeigen .... das ist essentiell für die Weiterfinanzierung und zeitlich dringend. Johanna und ich haben heute (Montag 2.11.) besprochen, dass wir ab dem 10.11. gerne die Webseite "vermarkten" wollen. Dafür sind noch einige Dinge zu erledigen. Für diese Woche sehe ich folgende Prios ... (teils von oben übernommen):

1) Die aktuell fertigen Indikatoren aus dem D-Ordner hochladen!
2) Bei den Ländervergleichen die Möglichkeit bieten, mehr bzw. andere Länder auszuwählen.
3) Die nächsten Filter einbauen: Ministerien, Offiziell/Inoffiziell
4) Die Long description Deutsch  - bei den Einzelindikatoren - sichtbar machen und auch die Kurzbeschriftung im Design ändern. Ich denke die Kurzbeschriftung sollte etwas größer sein. 
5) Bei der Einzelindikator Viz: die Balken breiter machen und die Beschriftung lesbarer. Außerdem sollten die Länder, für die es keine Daten gibt, nicht sichtbar sein.
6) Footer (siehe Entwurf)
![entwurf footer](https://cloud.githubusercontent.com/assets/8308986/10862142/4b822686-7f9c-11e5-97b1-d3d3d4f28820.JPG)
Johanna überlegt sich noch mehr zu Design von Footer und Header ... mit in den Footer soll natürlichlich auch unsere email und Twitter account @2030WatchDe
7) Uns (Sina, Johanna,Claudia) zeigen wie man D-Dokumente/Indikatoren aus dem gescored Ordner hochlädt!

**Comment by jengeb** [comment]
Not relevant anymore, because there will be a new webpage soon.
