### ISSUE TITLE
Prios für die 3 Novemberwoche

### ISSUE THREAD

**Issue by ClaudiaSchwegmann** [okfde/2030-watch.de#43]
Hier die Prios für die kommende Woche für die Webseite
1) Erweiterung der Darstellung von Metadaten (Datenquelle, Jahr?)
2) Konzept für die 3/ 4. Ebene. Die vierte Ebene sollte nur sichtbar sein, wenn es tatsächliche Zusatzinformationen gibt. Zusatzinformationen wären Kontextvisualisierungen (eine oder mehrere). Weitere Elemente der Webseite sollten sein:
- ein Space für Datenpaten
- Zusatzdokumente/Hintergrunddokumente
- Kontakt zu Experten
- Datagaps.
  Bei allen vier Punkten bin ich mir nicht sicher, ob sie auf der dritten oder der vierten Ebene sein soltlen. 

3) Im Text könnten wir mit Teasern arbeiten: also dass man nur 1-3 Sätze pro Abschnitt lesen kann und dann zum weiterlesen aufklappen müsste. @Johanna wollte dazu weiter überlegen.

4) Kontextvisualisierungen: Die Daten zu den Waffenexporten vom Entwicklungsbarometer sollten wir auf unserer Webseite integrieren.

5) Yetzt hat angeboten mal Vorschläge zur weiteren Verbesserung der Webseite zu machen. Er wird sich dazu mit Dir Christian absprechen. Das einfachste ist wohl, wenn er einen Branch auf github macht oder?

6) Wir sollten jetzt bald ein Favicon für die Webseite haben. Ich schlage vor, den SDG-Farbkreis.

7) Christian, Du hattest uns ja bereits einen Link gesandt, wo wir alle online Indikatoren einsehen können. Es wäre gut, wenn wir so bald wie möglich eine englische Liste aller Indikatoren auch auf der Webseite bereitstellen können. Diese Liste sollte Folgendes beinhalten: Indicator name, short description english, unit, indicator source, data source, most recent year.

8) Wir brauchen eine Einbindung von Twitter und Facebook, so dass man auch einen vorgefertigten Tweet rausschicken kann. Vielleicht kann yetzt das auch machen?

9) Mittelfristig müssen wir uns über das Management der Daten Gedanken machen? Brauchen wir ein Content Management System? Vor allem, um die Aktualisierung der Daten auch dezentral durch Datenpaten zu ermöglichen? Oder gibt es dazu andere Alternativen?

Soweit erstmal... bitte gerne kommentieren wo nötig!

Johanna, Sina und ich arbeiten an Öffentlichkeitsarbeit, Verbesserung der Daten und Texte, weitere Recherche der Daten und Outreach. Sina arbeitet sich weiter in Datenvisualisierungen ein. Claudia fügt bisherige Texte zu einem technical paper zusammen. Claudia klärt auch, inwiefern wir Discuss für Online Diskussionen zu Indikatoren nutzen können.
Ab Montag sollten wir die CDI Datensätze aktualisieren  - Montag kommt der neue Commitment to Development Index raus!

**Comment by jengeb** [comment]
This issue refers to the old/current webpage. There will be a new version soon.
