### ISSUE TITLE
Prios Dezember

### ISSUE THREAD

**Issue by ClaudiaSchwegmann** [okfde/2030-watch.de#52]
A) Wir brauchen eine Liste aller Indikatoren die online sind, inklusive Kurzbeschreibung, Datenquellen, Indikatortyp, SDG. Diese Liste sollte möglichst sortierbar sein (mindestens aber nach SDGs sortiert) und downloadbar. Viele mögliche Kooperationspartner brauchen solch eine Liste. Wirklich wichtig! 

B) Vierte Ebene: Entwurf hier auf Drive: https://docs.google.com/presentation/d/1cFDe5potjyz0V995aw9Gd65JLUKiQ-x2EE7bulo0gBs/edit#slide=id.p8

C) Kleinzeug:
1. Impressum (der ganze rechtliche Kram)
2. Korrektur im Text über der ersten Viz: "Die kürzlich von allen UN ...."  ersetzen durch "die im September 2015 von allen UN...2
3. "Über uns" statt "OKF DE". Und Text Ergänzung zum Projektteam. Den Text über die OKF sollten wir kürzen und an Helenes Vorschlag anpassen. https://docs.google.com/document/d/13HWJOIn3JM4RYxLNK4ztsrx_ljF3PyOIsTZh_VVP2ic/edit
4. Einleitungstext unter Deutschland wird nachhaltig größer als die nachfolgenden Texte (darin auch nichts kursiv gedrucktes)
5. Erklärtext zu den Grafiken in Boxen
6. Farbskala eher am rechten Rand der Hauptgrafik, damit der Hoovertext der Punkte direkt unter der Grafik angezeigt wird.
7. Wenn sich Auswahlmöglichkeiten aufklappen sollten sie auch wieder einklappen (z.B. Auswahl der Indikatoren oder gehe zu im Menü)
8. Erste Viz: 
Zu Verantwortung. 
Statt einer Bullet point list hätte ich die Ministerien lieber als kleine Kacheln. Jeweils 3 nebeneinander, 5 Reihen. Unter den Kacheln sollte eine Erklärung stehen: "Die Umsetzung aller SDGs liegt in der Verantwortung der gesamten Bundesregierung. Nichtsdestotrotz liegen einzelne Indikatoren in der besonderen Verantwortung einzelner Ministerien. Hier können die Indikatoren nach dieser besonderen Verantwortung gefiltert werden."

Zu Typ. Text unter den beiden Filteroptionen. "2030-Watch enthält offizielle Indikatoren und inoffizielle Indikatoren. Die offiziellen Indikatoren umfassen Vorschläge der UN Expertengruppe für Indikatorvorschläge, des Sustainabel Development Solutions Networks und der bestehenden deutschen Nachhaltigkeitsstrategie. Die inoffiziellen Indikatoren stellen Indikatorvorschlag der Open Knowledge Foundation dar. Diese Vorschläge sind zum Teil in Abstimmung mit zivilgesellschaftlichen Experten entwickelt worden." Falls der Text zu lang ist, sollte nur ein Teaser angezeigt werden.

Bei diesen Empfehlungen bin ich mir nicht sicher - To be discussed mit Johanna :) - ii und iii verstehe ich nicht. 
i. Button bei der Hauptgrafik: 'Verändere die Farben der Kreise'  
ii. Gleiche Farbe in der Menüleiste: grau oder schwarz...
iii Logo in der Menüzeile größer oder weg. Wirkt so verloren...

D) Zusätzliches falls Zeit ist
- Die Dropdown Listen beim Ländervergleich sollen alphabetisch sein.
- Wir brauchen mittelfristig Statistiken zu Besuchern der Webseite
- Bei der dritten Visualisierung sollte zuerst immer Deutschland etwas hervorgehoben sein, dass man es finden kann.
- Die Dropdownliste der Einzelindikatoren über dem Balkendiagramm sollte besser strukturiert werden, z.B. nach SDGs oder so. Im Moment ist sie nicht sehr übersichtlich - vor allem wenn die Liste noch länger wird, wird es schwierig.
- Die zweite Dropdownliste über dem Balkendiagramm kann meiner Meinung nach weg. Der Mehrwert der unterschiedlichen Sortierung ist meiner Meinung nach gering. Den Platz könnte man glaube ich besser nutzen.
- Eine deutsche und englische Liste aller Indikatoren sollte runterladbar sein.
- Social Media Einbindung: Twitter und Facebook
- Zu den SDG Kacheln und Opacität (?). Ich fände es wirklich schöner, wenn die Kacheln gar nicht blass wären und die Hervorhebung beim Hoovern anders funktioniert.

**Comment by jengeb** [comment]
This issue refers to the old/current webpage. There will be a new version soon.
